essen = [
    "einen Wirsingeintopf",
    "einen Lahmacun",
    "eine Portion Kartoffelbrei",
    "Spinat",
    X"Astronautenfutter",
    S"ein Snickers",
    S"einen Mars-Riegel",
    "eine Brezel",
    X"eine Portion Gagh",
    "einen Seitan Döner",
    "einen Teller Spaghetti Bolognese",
    "einen Teller Spaghetti mit Käsesahnesoße",
    "einen Obstteller",
    S"eine Hand voll Gummibärchen",
    S"eine Schale mit Kartoffelchips",
    "zwei Käsebrote",
    "Okonomiyaki",
    "zwei Stück Erdbeertorte",
    "feuriges Chili sin Carne",
    "ein fluffiges Rührei",
    "eine leckere Pizza",
    "einen frischen Gurkensalat",
    "einen großen Chefsalat",
    X"eine übelriechende Käsesuppe",
    "Schwarzwurzel und Kartoffelbrei",
    "ungarisches Gulasch",
    "Spaghetti mit Soja-Bolognese",
    "ein original französisches Ratatouille",
    "einen sahnigen Schokopudding",
    "arme Ritter",
    "Pommes mit Majo",
    "leckeren Kartoffelauflauf",
    "einen Toast Hawaii",
    "indisches Gemüse Curry",
    "einen Planted-Gyrosteller mit Tzatziki",
    "ein Pilz-Risotto",
    S"ein hart gekochtes Ei",
    S"vier Pralinen mit Nougatfüllung",
    "ein paar Mini-Frühlingsrollen",
    "würziges Sauerkraut",
    "ein Schälchen Apfelmus",
    "Bratkartoffeln",
    "asiatisches Wokgemüse",
    S"einen fruchtigen Lolli",
    "einen Teller mit süßem Milchreis",
    "eine Lasagne",
    "chinesisch gebratene Nudeln",
    "ein Tomaten-Baguette",
    X"fünf mexikanische Tacos",
    S"einen Blaubeermuffin mit Sahne",
    X"eine Hand voll alte Erdnüsse",
    "eine Mango",
    S"einen Erdnussbutterriegel",
    S"eine Schachtel Lebkuchen",
    "eine Portion Falafel mit Hummus",
    "ein feuriges Chili con Soja",
    "einen Teller getrocknete Jackfruchtstücke",
    S"eine Packung Choco-Fresh",
    "einen Teller Spaghetti mit Gorgonzolasoße",
    S"fein geschnittene Karottenstückchen mit laktosefreiem Frischkäse",
    "einen Big Vegan TS",
    "einen McPlant",
    "einen Teller voll Burritos",
    "eine Portion handgerolltes Sushi",
    "ein Butterbrot",
    "eine Schnittlauch-Brezel",
    "einen Teller szegediner Gulasch",
    "eine Portion Avocado Maki",
    "eine Portion Konjaklachs-Maki"
    "eine Spinatlasagne",
    "einen Teller vegetarisch gefüllte Paprika",
    "einen Teller gefüllte Zucchini",
    "ein Schinken-Käse-Omelett",
    "Chop Suey",
    "ein großes Stück Tofurducken",
    "einen Teller Spaghetti Aglio e Olio",
    "Nudeln mit Pesto",
    "einen Teller Paella",
    "einen Berg Pfannkuchen",
    "einen Teller Belgische Waffeln mit Schokosoße",
    "eine Waffel mit Puderzucker",
    "Grießbrei mit Amarena Kirschen",
    "einen Kaiserschmarrn mit Apfelmus",
    "Palatschinken mit Marillenmarmelade und Staubzucker",
    S"eine Tüte Maiswaffeln",
    X"einen Handkäs mit Musik",
    "eine Schale Grießbrei mit Nutella",
    "ein Gefäß mit Wan Tan",
    X"die Reste von gestern",
    "frittierten Tofu auf Eierreis",
    "Kürbiskernbratlinge",
    S"eine Handvoll Studentenfutter",
    S"ein Schüsselchen Studentenfutter ohne Rosinen",
    S"eine Handvoll Knabbersoja",
    S"eine Schachtel Pralinen",
    X"ein Osternest mit Ostereiern",
    "veganen Räucherspeck mit frischen Zwiebeln",
    "eine große Portion Tortellini mit Frischkäsefüllung",
    "ein rustikales Krustenbrot mit Bergkäse",
    X"Zuckerwatte mit Einhorngeschmack",
    "einen Eimer buntes Popcorn",
    "dampfenden Kaiserschmarrn",
    "Grießbrei mit roter Grütze",
    "brasilianischen Schwarzbohnen-Eintopf (feijoada)",
    X"einen ganzen Karpfen mit Gräten",
    X"eine abgelehnte Petition",
    X"eine dreistöckige Tofu-Turbulenz",
    X"eine Kelle kalte Gulaschsuppe",
    X"eine Schale tumultuöses Tiramisu",
    "eine Portion Reispudding",
    S"ein Dreierpack Ahoj-Brause",
    XX"radioaktive Pfifferlinge aus den Prypjatsümpfen",
    X"eine Portion zappligen Zucchiniauflauf",
    "einen Teller selbstgedrehte Zucchini-Nudeln",
    "mildes Möhrenmischmasch",
    "gegrillten Kürbis",
    "knusprige Frühlingsrollen mit Dip",
    "drei frische Onigiri",
    X"den Kraftriegel der deutschen Arbeiterklasse",
    X"Bratwurst mit Sauerkraut",
    X"ein Bündel Petersilie",
    "eine Schale Stachelbeerkompott",
    X"Stulle mit Brot",
    X"ein Stück kichernden Käsekuchen mit Himbeeren",
    S"eine Handvoll rohe Mandeln",
    "entzückendes Erbsengemüse",
    "Eierlikörkuchen mit vollständig ausgebackenem Eierlikör",
    X"drei Stücke traurige trockene Torte",
    "Wassermelonensalat in einer ausgehöhlten Wassermelone",
    X"abgelaufenes Knäckebrot, das nicht mehr knackt",
    "einen runderneuerten Obstkuchen mit upgegradeten Erdbeeren",
    X"Rock`n Roll-Rouladen",
    X"eine ganze Benjamin-Blümchen-Torte",
    X"eine Schüssel chaotische Chili-sin-Carne",
    "sauer eingelegten Spargel in Aspik",
    X"ein unidentifizierbares Experiment mit zu viel zerlaufener Butter",
    X"einen Gruß des Küchenlehrlings",
    X"einen Klumpen Teig, der an einen Kuchen erinnert,",
    "gedünsteten Brokkoli",
    "gebratenes Gemüse mit Erdnusssoße",
    "Quinoasalat mit feinen Tomaten",
    "einen italienischen Klassiker mit einem ~Spritzer~ Olivenöl",
    "ein selbst gebackenes Kürbiskernbrötchen",
    "ein knuspriges Laugendreieck",
    X"eine Wagenladung voll Spritzgebäck",
    "einen Döner mit Mais",
    X"eine ominöse grellgrüne Grütze",
    X"einen benutzten Teller",
    X"Schlagsahne direkt aus der Sprühdose",
    X"ein Glas Erdnussbutter und einen Löffel",
    X"einen halb gegessenen Pfannkuchen",
    X"eine nicht ganz perfekte Crème Brûlée",
    "eine Portion Nudelsalat",
    X"eine rohe Knoblauchzehe",
    "Wok-Gemüse mit Udonnudeln",
    "eine Schüssel Ramen mit einem Alibi-Ei",
    "eine vegane Kringelbratwurst mit Gurkensalat",
    "ein Stück Lasagne nach einem alten Rezept",
    X"ein Stück Hochzeitstorte mit 2kg Fondant",
    X"eine Portion unauthentische vietnamesische Kost",
    X"frittiertes Besteck",
    "gut gewürzten Linsensalat",
    "einen Rocula-Wrap mit gehackten Datteln",
    S"drei klebrige Ricola-Hustenbonbons",
    X"einen von Schnecken zerfressenen Kopfsalat",
    X"eine Portion von Kronks Spinattaschen",
    "ein Räuchertofu in Fischform",
    S"einen Teller Empörung",
    X"Nudeln, die elf Minuten gekocht wurden",
    "ein köstliches Drachenfrucht-Dessert",
    X"die Reste der Woche",
    X"einen Eimer frittiertes Tempeh",
    "überbackene Champignons mit Aubergine",
    X"eine gefährlich wackelnde Götterspeisetorte",
    S"eine Auswahl an Käsesorten mit Weintrauben",
    "eine Schüssel cremige Kürbissuppe",
    "einen dampfenden Gemüsemuffin",
    "eine Scheibe frisches Bananenbrot",
    "eine ordentliche Käsestulle",
    S"ein Stück glasierten Zitronenkuchen",
    S"einen hübsch verzierten Cupcake",
    S"einen drolligen Cake-Pop",
    X"eine erfrischende ganze Gurke",
    "eine Pfanne mit Zucchini-Feta-Gemüse",
    "Spaghetti mit Linsen-Bolonese",
    "ein Stück Lavendel-Honig-Torte",
    "einen Teller knusprige Kroketten",
    "einen Teller Spargel mit Sauce Hollandaise",
    "Zopfbrot",
    X"eine Portion Kimchi, extra scharf",
    "Tteokbokki vom Streetfoodmarkt",
    X"einen Teller glitschige Süßkartoffelnudeln",
    "eine extra große Pizza mit Paprika",
    X"eine Portion Bangers and Mash",
    S"einen Donut mit Ahornsirup",
    "einen Teller Moussaka",
    "ein großes Stück Red-Velvet-Kuchen",
    "eine Portion Pelmeni mit Schmand",
    "eine dampfende Pfanne Paella",
    "ein knuspriges Langos mit Salz und Öl",
    S"einen Spieß frisch gebackener Kartoffelchips mit Salz und Essig",
    X"eine ganze Ananas",
    "einen prall gefüllten Frühstücksburrito",
    "eine mehr oder weniger gelungene Turducken",
    S"eine Handvoll getrocknete Früchte",
    "Gemüsestreifen mit Hummus-Dip",
    S"Bertie-Botts-Bohnen in den sonderbarsten Geschmacksrichtungen",
    S"drei brodelnde Kesselküchlein",
    S"eine Schale festklebender Bonbons aus Omas Schrank",
    X"Gourmet-Katzenfutter",
    "ein Omelett mit Pilzen und Cheddar",
    "eine Pizza Supreme mit gefülltem Rand",
    "zwei französische Tacos mit algerischer Soße",
    S"eine Packung Schokofrösche",
    "eine deliziöse Schüssel Bouillabaisse",
    X"ein schmieriges Sandwich mit zu viel Remoulade",
    S"ein Hörnchen vom nächsten Bäcker",
    "frisch gebackenes Fladenbrot und Oliven",
    "ein extravagantes Spezialgericht mit Goldblättchen und Trüffel",
    S"eine Schale Nachos mit Käsesoße",
    S"eine Tüte süßes Popcorn",
    S"eine Tüte salziges Popcorn",
    TTTTT"einen hellblauen Slushie mit Strohhalm",
    X"eine übergroße Erdbeere mit Sahnehäubchen",
    X"einen großen Teller Fingerfood mit ungünstig platzierten Spießchen",
    X"ein fest geschlossenes Glas saure Gurken",
    "eine winzige Portion Ratatouille mit einem einzelnen Strang Schnittlauch oben drauf",
    S"einen Kaugummi mit Drei-Gänge-Menü-Geschmack",
    X"eine Portion rohe Po-ta-toes (boil'em, mash'em, stick'em in a stew)",
    "eine kleine Schale Honigpudding",
    "eine Portion dreifach frittierte Pommes mit Mayonnaise",
    X"einen triefenden Burger",
    S"süße Siruptörtchen",
    S"eine große Wolke Zuckerwatte",
    "einen Teller Arme-Ritter-Banane",
    "ein perfekt zubereitetes Kartoffelgratin",
    "eine Portion Konjak-Garnelensalat",
    "eine gut pürierte Smoothie-Bowl",
    "einen Corndog",
    "eine Portion welliger Pommes aus dem Schwimmbad-Bistro",
    "eine feine, mit Frischkäse gefüllte, Blätterteigrolle",
    "eine frisch gebackene Kürbispastete",
    "eine schokolierte Birne am Stiel",
    "ein Stück Bienenstichkuchen",
    S"ein Blech Rosinenfladen",
    S"drei Schaumküsse mit verschiedenen Geschmacksrichtungen",
    "ein Stück deftigen Gemüsekuchen",
    S"eine Tüte Chiasamen zum Knabbern",
    X"eine Tasse Spargelcremesuppe aus der Tüte",
    "dampfende Kartoffelspalten mit Kräuterquark",
    "eine Portion gedünsteten Blumenkohl",
    "ein Blech saftiger Brownies",
    "eine teure Trüffelspezialität",
    "einen Teller Bouletten und grüne Bohnen",
    "eine Portion Bohnen und Zwiebeln",
    S"eine Familienpackung Toffifee",
    S"eine Schale Süßigkeiten von letztem Halloween",
    "eine Croustade",
    X"einen ganzen Atlantic-Gigant Kürbis",
    X"eine kandierte Zwiebel",
    "Reisporridge mit Frühlingszwiebeln",
    X"einen Reiskocher und eine Packung Reis",
    X"einen deckenhohen Stapel Pfannkuchen und eine Flasche Ahornsirup",
    "einen gegrillten Gemüsespieß",
    "ein Panna Cotta mit Aprikosenkompott",
    "eine Schale liebevoll geschnittenes Obst",
    "ein halbes Brötchen mit grober Lebervurst",
    X"eine täuschend echte Rolle Toilettenpapier, aber es ist Kuchen",
    "eine große Auswahl an Sushi-Spezialitäten und etwas Sojasoße",
    "eine schmackhafte Ingwerwurzel",
    "eine Portion Süßkartoffelpommes mit Mango-Chutney",
    "eine gut abgeschmeckte Portion Kartoffeleintopf",
    "eine Bockwurst mit Ketchup",
    "eine Portion Schmorgurken",
    X"ein unpraktisch hoch belegtes Sandwich",
    X"eine Schale kalte Kartoffeln von gestern",
    X"das Hologramm eines königlichen Festmahls",
    X"eine Tube Astronautennahrung",
    X"einen quadratischen Nährstoffwürfel der Zukunft",
    X"ein paar aufgeplatzte Wiener Würstchen",
    "ein Körnerbaguette und Häckerle",
    X"Gesundheitssuppe in einer Flasche",
    "eine Scheibe Pumpernickel mit einem hartgekochten Ei",
    "authentisches indisches Curry",
    X"eine Schüssel Soup-Soup-Soup",
    S"kandierte Früchte am Stiel",
    S"ein Päckchen Gummibärchen für die Tapferkeit",
    X"die Überreste vom letzten Abendmahl",
    X"ein ausgeplündertes Überraschungsei",
    X"einen mexikanischen Burrito mit viel zu dicker Tortilla",
    X"ein verschmähtes Stück der Krönungsquiche",
    "fischförmiges Gebäck mit roter Bohnenfüllung",
    X"ein dezent angebrütetes Dinosaurierei",
    "einen köstlichen Auberginenauflauf",
    X"eine Handvoll hartgekochter Wachteleier",
    "eine türkische Pizza",
    "einen Falafeldöner mit extra Soße",
    X"eine Plan 9-Tomate aus dem Weltall",
    S"eine plattgedrückte Mozartkugel",
    "einen Teller Pasta Primaverda",
    "eine heiße Ofenkartoffel",
    "eine Pizza mit riesiger Ananasscheibe",
    "eine halbe Pizza mit extra Knoblauch",
    X"eine krachende Kaisersemmel",
    X"einen riesigen Königsberger Klops mit Kapernfüllung",
    X"einen unverständlichen Gruß aus der Küche",
    X"ein schokoladiges Miniaturmodell des Sonnensystems mit Pluto als Kirsche",
    X"den kulinarischen Epitaph des Küchenchefs",
    X"ein halsbrecherisches Stuntmanöver mit klapperndem Geschirr",
    X"einen nicht wie die Abbildung auf der Karte aussehenden Burger",
    "einen echten Cheeseburger zum Mitnnehmen",
    S"einen einzelnen karamellisierten Marshmallow",
    "einen seltenen niederländischen Bergkäse",
    S"ein Schokoladentörtchen mit geschmolzenem Kern",
    S"eine Partypackung Salzstangen",
    "ein deftig belegtes Laugenbrötchen",
    "zwei Gemüsefrikadellen mit Tomatensalat",
    X"die Reste der gestrigen Grillfeier",
    X"in Ketchup ertränkte Pommes",
    "eine Portion Kartoffelstampf mit Zwiebelsoße",
    "eine Portion Konjaklachs in Kräutersud",
    "Kaviar in einer Schale aus purem Gold",
    X"die Experimente eines Amateur-Koches",
    X"eine Dose Mais und einen Löffel",
    X"Spaghetti mit einer Fertigsoße",
    "Nudeln mit selbstgemachtem Pesto",
    "eine Portion Kartoffeln mit Kohlrabi-Möhren-Gemüse",
    "einen Schokobrunnen und eine Schale Obst",
    "ein deftiges Käse-Fondue",
    X"ein paar Gottes Zorn hervorrufende Maultaschen",
    "eine mittelgroße Pizza mit Brokkoli und diversem Gemüse",
    "zwei dampfende v-Schnitzel Cordon bleu von Rügenwalder Mühle",
    "hübsch angerichtete Antipasti",
    "ein paar Scheiben Ciabatta mit Bruschetta",
    X"eine überreife Banane mit braunen Stellen",
    "einen fruchtigen Salat mit Honigmelone",
    X"ein Frühstücks-Abendessen",
    X"die abgelaufene Srirachasoße aus dem Kühlschrank",
    "ein frisches Gemüsebrötchen",
    X"eine Dose Spargel mit kürzlich abgelaufenem Verfallsdatum",
    "Kartoffelpuffer mit Apfelmus",
    X"Spinat mit gummiartigem Rührei",
    "Spinat mit knusprigen Gemüsepommes",
    "eine Schale duftender Fenchelsuppe",
    X"eine Schale Fertigsalat aus dem Supermarkt",
    "eine Schüssel Nudel-Rosenkohl-Eintopf",
    "eine Schale Wrukeneintopf",
    "eine glasierte Streuselschnecke",
    "ein fruchtiger Mandarinenkuchen mit Teigstreuseln",
    "ein Stück Fantakuchen",
    "ein Stück wolkigen Schokoladenkuchen mit Puderzucker",
    S"einige frittierte Quarkbällchen",
    S"eine Tüte Mutzen vom Weihnachtsmarkt",
    "knusprige Süßkartoffelpommes",
    "eine Portion überbackene Aubergine",
    "deftigen Eintopf in einem ausgehöhlten Brotlaib",
    S"eine Schale gesalzener Chips mit Salsa-Dip",
    "einen Tortilla-Sombrero mit Guacamole-Rand",
    "ein fürstliches Frühstück",
    "einen Korb frischer Croissants mit einer Auswahl an Marmeladen",
    S"zwei glasierte Donuts",
    "zwei gefüllte Donuts",
    X"zwei mit Senf gefüllte Donuts",
    S"eine Packung Minz-Tic-Tacs",
    X"einen Krabbenburger mit extra Gürkchen",
    X"ein Tablett mit Flugzeugessen",
    "einen gemischten Salat mit Radieschen",
    "zwei getoastete Waffeln",
    "Pflaumenkuchen mit Schlagsahne",
    X"ein dutzend Kartoffelknödel in Zwiebeltunke",
    X"sechs Eimer Kartoffeln",
    "einen Teller kalten Nudelsalat",
    "gefüllte Kartoffeltaschen mit würziger Soße",
    X"in Zitronenwasser gewaschene Algen mit Wasabi",
    "flambierte Crêpe Suzette",
    "ein komplettes Englisches Frühstück mit Black Pudding",
    "ein Nutellatoast mit Bananenscheiben",
    "eine Portion hervorragend abgeschmecktes Rührei",
    S"einen winzigen Muffin, der nicht so weich ist, wie er aussieht",
    X"ein Blech Papageienkuchen",
    X"eine schief gewachsene gelbe Paprika",
    "zwei gefüllte rote Paprikas",
    "einen Teller weißen Schichtkohl",
    "in Miso mariniertes und gebackenes Konjak-Fischfilet",
    X"eine Schale ungewürztes Erbsenpüree",
    "ein gegrilltes Tofu mit einer würzigen Tomaten-Curry-Soße",
    "gedämpfte Austernpilze mit knusprigen Pommes",
    X"einen Geburtstagskuchen mit zu wenig Kerzen",
    S"eine angebrochene Packung Oreos",
    X"das Leibgericht von Theodore Roosevelt",
    X"die Bestellung des Sitznachbarn",
    X"eine intergalaktische Spezialität",
    X"ein Rezept und passende Zutaten",
    X"einen Kuchen ohne Backpulver",
    "ein Stückchen Nusskuchen",
    "ein Stück Karottenkuchen mit Möhrchendeko",
    X"eine Portion unterwürzte Maccaroni mit Käse",
    "Seitan-Roast mit Yorkshire Pudding",
    S"die letzte Packung Schokolade",
    X"das fliegende Spaghettimonster mit extra großen Tempehbällchen",
    X"Albert Einsteins Lieblingsessen: Spaghetti",
    X"eine Packung Proteinpulver und Wasser",
    "eine Pizza ohne Rand",
    X"eine aufgeklappte Calzone",
    X"eine Pizza mit ausschließlich Rand",
    X"ein Haar in der Suppe",
    X"vier Töpfe cremiger Shiitake-Suppe",
    "eine Portion Brokkoli-Kartoffel-Gratin",
    X"eine von Javier Milei mit der Motorsäge zurechtgeschnittene Karotte",
    X"ein closed-faced Sandwich",
    "ein open-faced Sandwich",
    X"einen auslaufenden Kautschukbaum",
    X"ein Stück Sägespänekuchen",
    "einen Teller Englische Scones mit Marmelade",
    "eine Portion Kanadische Poutine",
    "eine Schüssel Wirsingkohl",
    S"eine Packung knusprige Käsestangen",
    X"zwei Körbe fettiger Pizzabrötchen",
    "einen ganzen Baumkuchen",
    "einen doppelten Burger mit extra Käse",
    X"eine Liste mit Restaurants in der Nähe",
    X"ein Töpfchen mit endlosem süßen Brei",
    "ein Stück frische Honigwabe",
    "einen Teller Rote-Beete-Suppe mit saurer Sahne",
    X"einen Salzstreuer mit fast abgeschraubtem Deckel",
    "zwölf knusprige v-Wings",
    X"ein fest geschlossenes Glas Mayonnaise",
    X"aufgetauten Kuchen vom letzten Jahr",
    X"ein Lebkuchenhaus mit eingestürztem Dach",
    "ein Stück Lebkuchen-Kuchen",
    "auf offenem Feuer zubereitetes Bulgogi",
    X"das bei Alfred Biolek von Blixa Bargeld gekochte Risotto",
    "das legendenumwobene Stück einer italienischen halbgetrockneten Tomate",
    X"eine Portion Obatzter",
    "eine Raffaello-Torte",
    X"einen Tortenheber ohne Torte weit und breit",
    X"Kartoffelpüree aus der Tüte",
    S"eine ganze Zitrone",
    X"eine Schale Elefantencreme",
    "geschichteten Schokopudding mit Waldbeeren",
    "zwei Stücke Champignon-Spinat-Lasagne",
    "eine Schale Haferbrei mit Honig",
    S"eine Schale Chiapudding mit Mango",
    S"eine weiche Birne",
    S"eine einzelne Walnuss",
    "eine Portion Reis mit Gemüsefrikassee",
    "Jasminreis mit gedünstetem Kaisergemüse",
    "drei westafrikanische Kichererbsenfrikadellen",
    S"gebackene Bananenbällchen mit Honig",
    X"billiges Sushi",
    "eine Auswahl an winterlichen Gebäcken",
    "Sommerrollen mit Teriyaki-Sauce",
    "einen duftenden Bratapfel",
    X"dreizehn üppige Zimtschnecken",
    "selbstgemachte Tacos mit Ortega-Soße",
    S"eine Schale geriebenen Gouda",
    "überbackenes Toast Hawaii",
    "einige Stücke russischen Zupfkuchen",
    "gezuckerte Krapfen",
    "eine heiße Apfeltasche",
    X"eine gigantische knusprige Krokette",
    "einen Teller mit Herzoginkartoffeln",
    "eine Bratwurst mit mediterranem Salat",
    "Nudeln mit Tomatensoße",
    X"des Wahnsinns knusprige Beute",
    X"eine hastig improvisierte Mahlzeit",
    X"eine Tube Zahnpasta mit Pfefferminzgeschmack",
    S"drei einzelne Kartoffelchips",
    S"eine Packung Kartoffelchips mit BBQ-Geschmack",
    "Schwammerlsuppe mit Knallpilzen",
    "einen Teller Nudeln mit Fenchelcremesoße",
    X"eine Portion Spaghetti mit fußballgroßen Hackbällchen",
    "zwei Stücke Pizza Margherita",
    X"ein modernes Kunstwerk aus Oliven",
    X"einen grünlich blubbernden Eintopf im Hexenkessel",
    X"einen deftigen Schlammkuchen",
    S"eine Auswahl verschiedenster Macarons",
    X"eine Dose Tomatensuppe",
    "ein frisches Dresdner Handbrot vom Weihnachtsmarkt",
    "knusprig gebackenen Seitan mit blanchierem Spargel",
    "eine große Portion vegane Gyoza",
    X"einen Zauberwürfel aus Gemüsestückchen",
    X"ein deckenhoch gestapeltes Sandwich",
    "zwei vegane Kohlrouladen",
    S"ein Stück knusprig-schokoladigen kalten Hund",
    "elegant gerollte Pfannkuchen mit Nutella",
    "elegant gerollte süße Eierkuchen",
    "elegant gerollten, deftigen Palatschinken",
    "elegant gerollte Plinsen mit Apfelmus",
    S"drei bunte Mochi am Stiel",
    X"die falsche Bestellung",
    X"die falsche Rechnung",
    "ein Koreanisches BBQ mit vierzig Nebengerichten",
    "mundgerechte Schnittlauch-Creme-Röllchen mit Dill",
    X"lauwarmen Kichererbsensalat",
    X"eine Dose Kidneybohnen und einen Löffel",
    "Shoyu-Ramen mit Pak Choi",
    X"eine Neuheit aus der modernen Molekularküche",
    X"ein Fünf-Sterne-Gericht und eine Lupe",
    "ofengebackenen Kürbis mit Spinathaube und Mandelsplittern",
    "ein halbes Brötchen mit Eiersalat",
    "ein halbes Brötchen mit v-Mett",
    "ein halbes Brötchen mit v-Fleischsalat",
    "ein halbes Brötchen mit Auberginencreme",
    "ein halbes Brötchen mit selbstgemachtem Kräuterquark",
    X"eine Schale Kräuterquark mit 50% Zwiebeln",
    "ein Toast mit Avocado und Ei",
    "mexikanische Pommes mit Guacamole und gehackten Tomaten",
    "eine Schale Pigs-in-a-Blanket",
    S"einige mit v-Speck umrollte Datteln",
    "einen hervorragend abgeschmeckten klassischen Salat",
    "Schnitzel mit Mischgemüse und Salzkartoffeln",
    S"ein überdimensional großes Nougatkissen",
    S"türkischen Honig in einer edel verzierten Schale",
    X"einen Döner ohne Brot",
    X"eine Erbsen-Mayonnaise-Pizza",
    X"den halben Kühlschrank",
    X"eine tiefgefrorene Packung Rosenkohl",
    "einen Apfel mit einer weißen und einer roten Backe",
    X"eine Schale dünne Suppe mit einem unpraktisch klobigen Holzlöffel",
    X"ein Tablett mit undefinierbarem Essen aus der Schulkantine",
    "ein drei-Gänge-Menü von Marco Pierre White",
    X"ein einzelnes rohes Hühnerei",
    X"eine Einladung zu einer Kochshow",
    X"einen Gutschein zu einem Kochkurs für Anfänger",
    X"die Wegbeschreibung zum nächsten Supermarkt",
    S"eine Tafel vegane Schokolade",
    "eine übergroße Mandarine",
    S"einen Laib Marzipanbrot",
    X"eine Packung Backpulver",
    "einen Teller Süßkartoffel-Kichererbsen-Curry",
    "zwei dampfende Falafel-Wraps",
    "ein durchgeweichtes Thunvischsandwich",
    "ein paar hartgekochte Eier im Glas mit Schnittlauch obendrauf",
    X"ein Schälchen mit Kaffeesatz",
    "eine Schale verführerischen Rucola-Kartoffelsalat",
    S"eine Packung Wikingerröllchen",
    S"einige harte Salzkaramell-Bonbons",
    X"nicht weniger als zwanzig Semmelknödel",
    X"einen klobig-klebrigen Proteinriegel",
    X"einen Berg fettige Ringelpommes",
    X"eine meterlange Gurkenspirale",
    S"Nougat in Form von Meeresfrüchten",
    "einen Topf Matzah-Ball-Suppe",
    "einen Laib geflochtenes Challah",
    S"eine XXL-Packung Merci",
    "vegane Pekingente mit Hoisin-Sauce",
    "gefüllte Zucchiniblüten",
    "ein Stück Zwiebelkuchen",
    "eine Schale Buchweizengrütze",
    X"eine Portion Schwadegrütze",
    "ein paar Holunderküchlein",
    X"eine Apfelpastete vom absolut bekloppten Johnson",
    "eine Schale Stachyssalat",
    "eine Apfelkaltschale",
    "eine Portion gebackenen Grießpudding",
    "diverse Beignets",
    "einen Teller Äpfel im Schlafrock",
    "zweienhalb Dampfnudeln",
    X"eine Farce für Suppe",
    "eine Schale Gemüsefumet",
    "einen Becher Graupen",
    "Hirse mit brauner Butter",
    TTTTTT"ein Glas Tee von Isländischem Moos",
    "einen Topf Morcheln",
    "eine mehrstöckige Hochzeitstorte",
    "eine Schüssel Pilzragout",
    "kandierte Pomeloschale",
    X"ein paar Stücke klebrigen Lokum",
    S"ein paar Trüffelpralinen",
    "einen großen Teller Rosenkohlsuppe",
    "eine Schale Pudding mit echtem Sago",
    X"alle veganen Bratwürste und alles Sauerkraut im Topf",
    "eine Schüssel Blaubeersuppe",
    "vier leicht getoastete Weißtoastscheiben",
    "ein Stück Zitronentarte",
    "steirische Apfeltorte",
    X"viel zu viele Waffeln",
    X"ein Stück Tante Mathildas Kirschkuchen",
    "eine köstliche Rolle Futomaki mit salzreduzierter Sojasauce"
    "ein Brötchen mit veganem Karottenlachs"
]
